# Wirepas oy

FROM ubuntu:18.04 as lxgw-base

RUN apt-get update --fix-missing --no-install-recommends \
    && apt-get install -y \
            build-essential \
            nano \
            wget \
            libsystemd-dev \
            dbus \
            python3 \
            python3-dev \
            python3-dbus \
            python3-gi-cairo \
            wget \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py && rm get-pip.py \
    && pip3 install --upgrade pip \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/*

FROM lxgw-base as sink-service-build
WORKDIR /app/
COPY sink_service/ .
RUN make clean && make && chmod +x build/sinkService

FROM lxgw-base as lx-gw

WORKDIR /app

COPY transport_service/ .
COPY utils/com.wirepas.sink.conf /etc/dbus-1/system.d/
COPY utils/extwirepas.pem /etc/extwirepas.pem
COPY --from=sink-service-build /app/build/sinkService /usr/local/bin/sinkService

ENV WM_LX_GW_VERSION="*tar*"
RUN pip3 install wirepas_messaging-${WM_LX_GW_VERSION}
RUN pip3 install wirepas_gateway-${WM_LX_GW_VERSION}


# Environment
ARG WM_SERVICES_HOST
ARG WM_SERVICES_MQTT_PORT
ARG WM_SERVICES_MQTT_USER
ARG WM_SERVICES_MQTT_PASSWORD
ARG WM_SERVICES_CERTIFICATE_CHAIN

ARG WM_SINK_UART_PORT
ARG WM_SINK_UART_BITRATE
ARG WM_SINK_ID

ENV WM_SERVICES_HOST=${WM_SERVICES_HOST:-"localhost"}
ENV WM_SERVICES_MQTT_PORT=${WM_SERVICES_MQTT_PORT:-"1883"}
ENV WM_SERVICES_MQTT_USER=${WM_SERVICES_MQTT_USER:-"mqttuser"}
ENV WM_SERVICES_MQTT_PASSWORD=${WM_SERVICES_MQTT_PASSWORD:-"12sdftat3089ajoiausd+91as12"}
ENV WM_SERVICES_CERTIFICATE_CHAIN=${WM_SERVICES_CERTIFICATE_CHAIN:-"/etc/extwirepas.pem"}
ENV WM_SERVICES_GATEWAY_ID=${WM_SERVICES_GATEWAY_ID:-""}

ENV WM_SINK_UART_PORT=${WM_SINK_UART_PORT:-"/dev/ttyACM0"}
ENV WM_SINK_UART_BITRATE={WM_SINK_UART_BITRATE:-"125000"}
ENV WM_SINK_ID=${WM_SINK_ID:-"0"}

ENV EXEC_TRANSPORT="wm-gw"
ENV EXEC_SINK=/usr/local/bin/sinkService

COPY utils/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

