repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
    - id: detect-aws-credentials
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: detect-private-key
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: '\.bat$'

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    - id: dockerfilelint
      stages: [commit]

-   repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
    - id: shell-lint

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6
