# Wirepas Oy
#
# Linux gateway
#

version: '3'
services:

    wm-sink:
        container_name: wm-sink
        image: wirepas/gateway-rpi
        build:
            context: ../..
            dockerfile: container/arm/Dockerfile

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../wm_gateway.env

        volumes:
            - /dev:/dev
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
           driver: journald

        command: sink

    wm-transport:
        container_name: wm-transport
        image: wirepas/gateway-rpi
        build:
            context: ../..
            dockerfile: container/arm/Dockerfile

        user: root
        privileged: true
        stdin_open: true
        tty: true

        restart: always
        env_file:
            - ../wm_gateway.env
        environment:
            - PYTHONUNBUFFERED=true

        volumes:
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

        logging:
            driver: journald

        command: transport
